version: '3.1'

services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.1
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./mongo.env
    volumes:
      - ./../backend/db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro
      - datadb:/data/db
    # command: --replSet rs0
    # depends_on:
    #   - mongodb_replica
  
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    env_file:
      - rabbit.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_conf/10-defaults.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - rabbit


volumes:
  datadb:
  rabbit:


# Config file(s): /etc/rabbitmq/conf.d/10-defaults.conf
#                 /etc/rabbitmq/conf.d/20-management_agent.disable_metrics_collector.conf